#
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Capybara/FeatureMethods:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/ContentTag:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_county_and_phone_number

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - countyportal
    - demo
    - staging
    - test
    - development

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*
    - spec/system/**/*
    - spec/routing/**/*

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
