defaults: &defaults
  secret_key_base: fc10280147ee153d098675a4275356656728b8606b6c2c8e9070f6c4af3a27885d66592af99cfc71ff6b76c1734c0b5044ad2fed5d1a470a0ce5258942bfb31d
  host: <%= ENV.fetch('HOST', 'localhost:3000') %>
  sendgrid_api_key: <%= ENV['SENDGRID_API_KEY'] %>
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_messaging_service_sid: <%= ENV['TWILIO_MESSAGING_SERVICE_SID'] %>

deployment: &deployment
  <<: *defaults
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['HOST'] || (ENV['HEROKU_APP_NAME'] ? "#{ENV['HEROKU_APP_NAME']}.herokuapp.com" : nil) %>

development:
  <<: *defaults

test:
  <<: *defaults

demo:
  <<: *deployment

production:
  <<: *deployment
