name: Test and Deploy
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: dafi
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: dafi
          POSTGRES_DB: dafi_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Dependencies
      - name: Install missing libs (This is slated to be added to the base image soon!)
        run: sudo apt-get -yqq install libpq-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v1-${{ runner.os }}-gems-
      - name: Install gems
        run: |
          gem install bundler -v $(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -1 | tr -d " ")
          bundle config path vendor/bundle
          bundle config --local build.sassc --disable-march-tune-native # https://github.com/sass/sassc-ruby/issues/146
          bundle install --jobs 4 --retry 3 --frozen && bundle clean
      # /Dependencies

      - name: Setup test database
        run: bin/rails db:test:prepare
      - name: Compile assets
        run: bin/rails assets:precompile
      - name: Run tests
        run: RAILS_ENV=test DISABLE_SPRING=1 bin/rspec

  deploy:
    name: "Deploy to Aptible"
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.APTIBLE_DRAI_ROBOT_SSH_PRIVATE_KEY }}"

      - name: Push to Aptible Staging
        run: |
          git remote add aptible-staging ${{ secrets.APTIBLE_STAGING_GIT_REMOTE }}
          git push aptible-staging master

      - name: Push to Aptible Production
        run: |
          git remote add aptible-production ${{ secrets.APTIBLE_PRODUCTION_GIT_REMOTE }}
          git push aptible-production master
